control_beneficiarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('registro.urls', namespace='registro')),
    url(r'^admin/', include(admin.site.urls)),
]

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
	##### Beneficiarios #####
    url(r'^$', views.Consultar_Beneficiarios.as_view(), name='consultar_beneficiarios'),
    url(r'^registrar_beneficiarios$', views.Registrar_Beneficiarios.as_view(), name='registrar_beneficiarios'),
    url(r'^editar_eneficiarios/(?P<pk>\d+)$', views.Editar_Beneficiarios.as_view(), name='editar_beneficiarios'),
    url(r'^borrar_beneficiarios/(?P<pk>\d+)$', views.Borrar_Beneficiarios.as_view(), name='borrar_beneficiarios'),
    ##### Direcciones #####
    url(r'^consultar_direcciones$', views.Consultar_Direcciones.as_view(), name='consultar_direcciones'),
    url(r'^registrar_direcciones$', views.Registrar_Direcciones.as_view(), name='registrar_direcciones'),
    url(r'^editar_direcciones/(?P<pk>\d+)$', views.Editar_Direcciones.as_view(), name='editar_direcciones'),
    url(r'^borrar_direcciones/(?P<pk>\d+)$', views.Borrar_Direcciones.as_view(), name='borrar_direcciones'),
)

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime


class Direccion(models.Model):
    nombre_direccion = models.CharField(max_length=200)

    def __unicode__(self):
        return self.nombre_direccion

    def get_absolute_url(self):
        return reverse('registro:editar_direcciones', kwargs={'pk': self.pk})


class Persona(models.Model):
    codigo = models.CharField(max_length=200)
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    cedula = models.CharField(max_length=12)
    telefono = models.CharField(max_length=200)
    estado = models.CharField(max_length=30)
    municipio = models.CharField(max_length=30)
    parroquia = models.CharField(max_length=30)
    direccion = models.ForeignKey(Direccion)
    observacion = models.TextField(max_length=1000)
    enviado_a = models.CharField(max_length=200)
    estatus = models.CharField(max_length=1)
    fecha_solicitud = models.DateField(default=datetime.now)
    fecha_respuesta = models.DateField(blank=True,null=True)

    def __unicode__(self):
        return self.nombres

    def get_absolute_url(self):
        return reverse('registro:editar_beneficiarios', kwargs={'pk': self.pk})

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Persona, Direccion
from django.forms import (
    TextInput, CharField, Select, RadioSelect, Textarea, CheckboxInput, DateTimeField
)
from datetime import *
from django.contrib.admin.widgets import AdminDateWidget

#date=datetime.now
date=datetime.today().strftime('%Y-%m-%d')

ESTATUS = (
    ('', 'Seleccione'),
    ('a', 'Aprobado'),
    ('e', 'En proceso'),
    ('n', 'Negado')
)

ESTADOS = (
    ('Mérida', 'Mérida'),
)

MUNICIPIOS = (
    ('', 'Seleccione'),
    ('Alberto Adriani','Alberto Adriani'),
    ('Andrés Bello','Andrés Bello'),
    ('Antonio Pinto Salinas','Antonio Pinto Salinas'),
    ('Aricagua','Aricagua'),
    ('Arzobispo Chacón','Arzobispo Chacón'),
    ('Campo Elías','Campo Elías'),
    ('Caracciolo Parra Olmedo','Caracciolo Parra Olmedo'),
    ('Cardenal Quintero','Cardenal Quintero'),
    ('Guaraque','Guaraque'),
    ('Julio César Salas','Julio César Salas'),
    ('Justo Briceño','Justo Briceño'),
    ('Libertador','Libertador'),
    ('Miranda','Miranda'),
    ('Obispo Ramos de Lora','Obispo Ramos de Lora'),
    ('Padre Noguera','Padre Noguera'),
    ('Pueblo Llano','Pueblo Llano'),
    ('Rangel','Rangel'),
    ('Rivas Dávila','Rivas Dávila'),
    ('Santos Marquina','Santos Marquina'),
    ('Sucre','Sucre'),
    ('Tovar','Tovar'),
    ('Tulio Febres Cordero','Tulio Febres Cordero'),
    ('Zea','Zea'),
)

PARROQUIAS = (
    ('', 'Seleccione'),
    ('Presidente Betancourt','Alberto Adriani - Presidente Betancourt'),
    ('Presidente Páez','Alberto Adriani - Presidente Páez'),
    ('Presidente Rómulo Gallegos','Alberto Adriani - Presidente Rómulo Gallegos'),
    ('Gabriel Picón González','Alberto Adriani - Gabriel Picón González'),
    ('Héctor Amable Mora','Alberto Adriani - Héctor Amable Mora'),
    ('José Nucete Sardi','Alberto Adriani - José Nucete Sardi'),
    ('Pulido Méndez','Alberto Adriani - Pulido Méndez'),
    ('Capital Andrés Bello','Andrés Bello - Capital Andrés Bello'),
    ('Capital Antonio Pinto Salinas','Antonio Pinto Salinas - Capital Antonio Pinto Salinas'),
    ('Mesa Bolívar','Antonio Pinto Salinas - Mesa Bolívar'),
    ('Mesa de Las Palmas','Antonio Pinto Salinas - Mesa de Las Palmas'),
    ('Capital Aricagua','Aricagua - Capital Aricagua'),
    ('San Antonio','Aricagua - San Antonio'),
    ('Capital Arzobispo Chacón','Arzobispo Chacón - Capital Arzobispo Chacón'),
    ('Capurí','Arzobispo Chacón - Capurí'),
    ('Chacantá','Arzobispo Chacón - Chacantá'),
    ('El Molino','Arzobispo Chacón - El Molino'),
    ('Guaimaral','Arzobispo Chacón - Guaimaral'),
    ('Mucutuy','Arzobispo Chacón - Mucutuy'),
    ('Mucuchachí','Arzobispo Chacón - Mucuchachí'),
    ('Fernández Peña','Campo Elías - Fernández Peña'),
    ('Matriz','Campo Elías - Matriz'),
    ('Montalbán','Campo Elías - Montalbán'),
    ('Acequias','Campo Elías - Acequias'),
    ('Jají','Campo Elías - Jají'),
    ('La Mesa','Campo Elías - La Mesa'),
    ('San José del Sur','Campo Elías - San José del Sur'),
    ('Capital Caracciolo Parra Olmedo','Caracciolo Parra Olmedo - Capital Caracciolo Parra Olmedo'),
    ('Florencio Ramírez','Caracciolo Parra Olmedo - Florencio Ramírez'),
    ('Capital Cardenal Quintero','Cardenal Quintero - Capital Cardenal Quintero'),
    ('Las Piedras','Cardenal Quintero - Las Piedras'),
    ('Capital Guaraque','Guaraque - Capital Guaraque'),
    ('Mesa de Quintero','Guaraque - Mesa de Quintero'),
    ('Río Negro','Guaraque - Río Negro'),
    ('Capital Julio César Salas','Julio César Salas - Capital Julio César Salas'),
    ('Palmira','Julio César Salas - Palmira'),
    ('Capital Justo Briceño','Justo Briceño - Capital Justo Briceño'),
    ('San Cristóbal de Torondoy','Justo Briceño - San Cristóbal de Torondoy'),
    ('Antonio Spinetti Dini','Libertador - Antonio Spinetti Dini'),
    ('Arias','Libertador - Arias'),
    ('Caracciolo Parra Pérez','Libertador - Caracciolo Parra Pérez'),
    ('Domingo Peña','Libertador - Domingo Peña'),
    ('El Llano','Libertador - El Llano'),
    ('Gonzalo Picón Febres','Libertador - Gonzalo Picón Febres'),
    ('Jacinto Plaza','Libertador - Jacinto Plaza'),
    ('Juan Rodríguez Suárez','Libertador - Juan Rodríguez Suárez'),
    ('Lasso de la Vega','Libertador - Lasso de la Vega'),
    ('Mariano Picón Salas','Libertador - Mariano Picón Salas'),
    ('Milla','Libertador - Milla'),
    ('Osuna Rodríguez','Libertador - Osuna Rodríguez'),
    ('Sagrario','Libertador - Sagrario'),
    ('El Morro','Libertador - El Morro'),
    ('Los Nevados','Libertador - Los Nevados'),
    ('Capital Miranda','Miranda - Capital Miranda'),
    ('Andrés Eloy Blanco','Miranda - Andrés Eloy Blanco'),
    ('La Venta','Miranda - La Venta'),
    ('Piñango','Miranda - Piñango'),
    ('Capital Obispo Ramos de Lora','Obispo Ramos de Lora - Capital Obispo Ramos de Lora'),
    ('Eloy Paredes','Obispo Ramos de Lora - Eloy Paredes'),
    ('San Rafael de Alcázar','Obispo Ramos de Lora - San Rafael de Alcázar'),
    ('Capital Padre Noguera','Padre Noguera - Capital Padre Noguera'),
    ('Capital Pueblo Llano','Pueblo Llano - Capital Pueblo Llano'),
    ('Capital Rangel','Rangel - Capital Rangel'),
    ('Cacute','Rangel - Cacute'),
    ('La Toma','Rangel - La Toma'),
    ('Mucurubá','Rangel - Mucurubá'),
    ('San Rafael','Rangel - San Rafael'),
    ('Capital Rivas Dávila','Rivas Dávila - Capital Rivas Dávila'),
    ('Gerónimo Maldonado','Rivas Dávila - Gerónimo Maldonado'),
    ('Capital Santos Marquina','Santos Marquina - Capital Santos Marquina'),
    ('Capital Sucre','Sucre - Capital Sucre'),
    ('Chiguará','Sucre - Chiguará'),
    ('Estánquez','Sucre - Estánquez'),
    ('La Trampa','Sucre - La Trampa'),
    ('Pueblo Nuevo del Sur','Sucre - Pueblo Nuevo del Sur'),
    ('San Juan','Sucre - San Juan'),
    ('El Amparo','Tovar - El Amparo'),
    ('El Llano','Tovar - El Llano'),
    ('San Francisco','Tovar - San Francisco'),
    ('Tovar','Tovar - Tovar'),
    ('Capital Tulio Febres Cordero','Tulio Febres Cordero - Capital Tulio Febres Cordero'),
    ('Independencia','Tulio Febres Cordero - Independencia'),
    ('María de la Concepción Palacios Blanco','Tulio Febres Cordero - María de la Concepción Palacios Blanco'),
    ('Santa Apolonia','Tulio Febres Cordero - Santa Apolonia'),
    ('Capital Zea','Zea - Capital Zea'),
    ('Caño El Tigre','Zea - Caño El Tigre'),
)

class PersonaForm(forms.ModelForm):

    codigo = forms.CharField(label="Código", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'001',
        }), required = True)

    nombres = forms.CharField(label="Nombres", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'Maria Gertrudiz',
        }), required = True)

    apellidos = forms.CharField(label="Apellidos", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'Parra Pérez',
        }), required = True)

    cedula = forms.CharField(label="Cédula", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'18902230',
        }), required = True)

    telefono = forms.CharField(label="Número telefónico", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'04263315899',
        }), required = True)

    estado = forms.ChoiceField(label="Estado", widget=Select(attrs={
            'class':'form-control input-md',
            #'style': 'min-width: 0; width: 100%; display: inline;',
        }), choices = ESTADOS)

    municipio = forms.ChoiceField(label="Municipio", widget=Select(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
        }), choices = MUNICIPIOS)

    parroquia = forms.ChoiceField(label="Parroquia", widget=Select(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
        }), choices = PARROQUIAS)

    '''
    direccion = forms.ChoiceField(label="direccion", widget=Select(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices=Direccion.objects.all().values_list('id','nombre_direccion'))
    '''

    observacion = forms.CharField(label="Observación", widget=Textarea(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; height: 100px; display: inline;',
      }), required = True)

    enviado_a = forms.CharField(label="Enviado a", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'value':'David Webb',
    }), required = True)

    estatus = forms.ChoiceField(label="Estatus", widget=Select(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices = ESTATUS)

    fecha_solicitud = forms.DateField(initial=datetime.now, widget= AdminDateWidget(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            #'disabled': 'disabled',
            'readonly': 'True',
    }), required = True)

    '''
    fecha_respuesta = forms.CharField(label="Fecha de respuesta", widget=TextInput(attrs={
            'class':'form-control input-md',
            'style': 'min-width: 0; width: 100%; display: inline;',
            'value':'0000-00-00',
    }),required = False)
    '''

    class Meta:

        model = Persona
        fields = '__all__'


class DireccionForm(forms.ModelForm):

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from registro.models import Persona, Direccion
from forms import PersonaForm, DireccionForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


#########################
##### Beneficiarios #####
#########################

class Consultar_Beneficiarios(ListView):
    model = Persona


class Registrar_Beneficiarios(SuccessMessageMixin,CreateView):
    model = Persona
    form_class = PersonaForm
    success_url = reverse_lazy('registro:consultar_beneficiarios')
    success_message = "Se registro el beneficiario con éxito"


class Editar_Beneficiarios(SuccessMessageMixin,UpdateView):
    model = Persona
    form_class = PersonaForm
    success_url = reverse_lazy('registro:consultar_beneficiarios')
    success_message = "Se actualizo el beneficiario con éxito"


class Borrar_Beneficiarios(SuccessMessageMixin,DeleteView):
    model = Persona
    success_url = reverse_lazy('registro:consultar_beneficiarios')
    success_message = "Se elimino el beneficiario con éxito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_Beneficiarios, self).delete(request, *args, **kwargs)


#######################
##### Direcciones #####
#######################

class Consultar_Direcciones(ListView):
    model = Direccion


class Registrar_Direcciones(SuccessMessageMixin,CreateView):
    model = Direccion
    form_class = DireccionForm
    success_url = reverse_lazy('registro:consultar_direcciones')
    success_message = "Se registro la dirección con éxito"


class Editar_Direcciones(SuccessMessageMixin,UpdateView):
    model = Direccion
    form_class = DireccionForm
    success_url = reverse_lazy('registro:consultar_direcciones')
    success_message = "Se actualizo la dirección con éxito"


class Borrar_Direcciones(SuccessMessageMixin,DeleteView):
    model = Direccion
    success_url = reverse_lazy('registro:consultar_direcciones')
    success_message = "Se elimino la dirección con éxito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Borrar_Direcciones, self).delete(request, *args, **kwargs)

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'datatables/js/jquery-1.11.3.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <!-- DatePicker
    ================================================== -->
    <link rel="stylesheet" href="{% static 'datepicker/css/jquery-ui.css' %}" type="text/css"/>
    <script src="{% static 'datepicker/jquery-ui.js' %}" type="text/javascript"></script>
    <!-- DataTables
    ================================================== -->
    <script src="{% static 'datatables/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'datatables/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Scripts - js
    ================================================== -->
    <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
  </head>
  <body>
    
    <!-- Navbar class
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Control de Beneficiarios</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!--li><a href="{% url 'registro:consultar_beneficiarios' %}">Lista</a></li-->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Beneficiarios <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'registro:registrar_beneficiarios' %}">
                    <i class="glyphicon glyphicon-link"></i>
                      Registrar Beneficiario
                    </a>
                </li>
                <li>
                  <a href="{% url 'registro:consultar_beneficiarios' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Consultar Beneficiario
                  </a>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Direcciones <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'registro:registrar_direcciones' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Registrar Dirección
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:consultar_direcciones' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Consultar Dirección
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar class -->

    <br />
    <br />
    <br />

    <!-- Container class
    ================================================== -->
    <div class="container theme-showcase" role="main">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
              <strong>
                {% if message.tags %}{% endif %}
                {{ message }}
              </strong>
          </div>
        {% endfor %}
      {% endif %}

      <!-- Well class
      ================================================== -->
      <div class="welll">
      {% block cuerpo %}
      {% endblock %}
      </div>
      <!-- End Well class -->

    </div>
    <!-- End Container class -->

  </body>
</html>

registro/templates/registro/direccion_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  ¿Estás seguro que quieres eliminar a: "<b>{{ object }}"</b>?
  <button class="btn btn-danger" type="submit">Borrar</button>
  <a href="/consultar_direcciones"><button type="button" class="btn btn-primary">Volver</button></a>
</form>
{% endblock %}

registro/templates/registro/direccion_form.html
{% extends "registro/base.html" %}
{% block titulo %}Registrar Dirección{% endblock %}
{% block cuerpo %}
<h1>Registrar Dirección</h1>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <br />
  <a href="/"><button type="button" class="btn btn-primary">Volver</button></a>
  <button class="btn btn-info" type="reset">Limpiar</button>
  <button class="btn btn-success" type="submit">Registrar</button>
</form>
{% endblock %}

registro/templates/registro/direccion_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de Direcciones{% endblock %}
{% block cuerpo %}
<h1>Lista de Direcciones</h1>
<table border="1px" id="example" class="display" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </tfoot>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td>{{ x.nombre_direccion }}</td>
    <td>
      <a href="{% url 'registro:editar_direcciones' x.id %}">
        <button class="btn btn-success">editar</button>
      </a>
      <a href="{% url 'registro:borrar_direcciones' x.id %}">
        <button class="btn btn-danger">borrar</button>
      </a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

registro/templates/registro/persona_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  ¿Estás seguro que quieres eliminar a: "<b>{{ object }}"</b>?
  <button class="btn btn-danger" type="submit">Borrar</button>
  <a href="/"><button type="button" class="btn btn-primary">Volver</button></a>
</form>
{% endblock %}

registro/templates/registro/persona_form.html
{% extends "registro/base.html" %}
{% block titulo %}Registrar Beneficiarios{% endblock %}
{% block cuerpo %}
<h1>Registrar Beneficiarios</h1>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <br />
  <a href="/"><button type="button" class="btn btn-primary">Volver</button></a>
  <button class="btn btn-info" type="reset">Limpiar</button>
  <button class="btn btn-success" type="submit">Registrar</button>
</form>
{% endblock %}

registro/templates/registro/persona_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de Beneficiarios{% endblock %}
{% block cuerpo %}
<h1>Lista de Beneficiarios</h1>
<table border="1px" id="example" class="display" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th></th>
      <th>Código</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Cédula</th>
      <th>Teléfono</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Parroquia</th>
      <th>Dirección</th>
      <th>Observación</th>
      <th>Enviado a</th>
      <th>Estatus</th>
      <th>Fecha de solicitud</th>
      <th>Fecha de respuesta</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th></th>
      <th>Código</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Cédula</th>
      <th>Teléfono</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Parroquia</th>
      <th>Dirección</th>
      <th>Observación</th>
      <th>Enviado a</th>
      <th>Estatus</th>
      <th>Fecha de solicitud</th>
      <th>Fecha de respuesta</th>
      <th>Acciones</th>
    </tr>
  </tfoot>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td></td>
    <td>{{ x.codigo }}</td>
    <td>{{ x.nombres }}</td>
    <td>{{ x.apellidos }}</td>
    <td>{{ x.cedula }}</td>
    <td>{{ x.telefono }}</td>
    <td>{{ x.estado }}</td>
    <td>{{ x.municipio }}</td>
    <td>{{ x.parroquia }}</td>
    <td>{{ x.direccion }}</td>
    <td>{{ x.observacion }}</td>
    <td>{{ x.enviado_a }}</td>
    {% if x.estatus == 'a' %}
      <td class="td_aprobado">Aprobado</td>
    {% elif x.estatus == 'e' %}
      <td class="td_en_proceso">En proceso</td>
    {% else %}
      <td class="td_negado">Negado</td>
    {% endif %}
    <td>{{ x.fecha_solicitud }}</td>
    <td>{{ x.fecha_respuesta }}</td>
    <td>
      <a href="{% url 'registro:editar_beneficiarios' x.id %}">
        <button class="btn btn-success">editar</button>
      </a>
      <a href="{% url 'registro:borrar_beneficiarios' x.id %}">
        <button class="btn btn-danger">borrar</button>
      </a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}